set SENDER_EMAIL = YOUR_SENDER_EMAIL_ADDRESS
set RECEIVER_EMAIL = YOUR_RECEIVER_EMAIL_ADDRESS
set SENDER_PASSWORD = YOUR_SENDER_EMAIL_PASSWORD
set PYTHON_PATH = YOUR_PYTHON_PATH
set SCRIPT_PATH = YOUR_SCRIPT_PATH

PYTHON_PATH SCRIPT_PATH SENDER_EMAIL RECEIVER_EMAIL SENDER_PASSWORD
pause